### ISSUE TITLE
Fix GlassBR bib References

### ISSUE THREAD

**Issue by smiths** [smiths/caseStudies#104]
While working on #31, I found that the entries in the bib file for the GlassBR SRS are lacking.  Can you please fix the following references: C1036, C1048, C1172, D4065, E631, and E1300.  The revised references should have a simple author field.  ASTM is fine as the author.  If the year is missing, the year should be added.  The citation names should also be changed to match the author year style.  That is, ASTM1999, or whatever.

**Comment by samm82** [comment]
Do you want the references in a specific order in the .bib file? Should they stay in the original order or be alphabetized? @smiths

**Comment by samm82** [comment]
Unless you want me to change ordering, I think this issue is closed. @smiths

**Comment by smiths** [comment]
Looks good.  Yes, we can close this issue.
