### ISSUE TITLE
Capitalization of Outputs in SRS

### ISSUE THREAD

**Issue by samm82** [smiths/caseStudies#108]
There is inconsistent capitalization of the list of outputs in Functional Requirement <span>#</span>6

![outputs](https://user-images.githubusercontent.com/35857611/42521095-eced6350-8435-11e8-8331-57c20aba8802.png)

EDIT: They should all be lowercase, as that's how they are typed in the rest of the document.

**Comment by smiths** [comment]
@samm82 you are correct.  I would like the capitalization to be consistent, but I don't really have a preference for which way to go.  They important thing is consistency.  We should follow how the capitalization is done throughout the rest of the document.  I believe this means that the sub-terms should have capitals.  For instance, I think Applied load should be Applied Load.  Can you please verify?  If the rest of the document uses this kind of capitalization, please propagate this change.

**Comment by samm82** [comment]
I thought they should be capitalized, but throughout the document, they're only capital if they're in a title and lowercase everywhere else, so I'll make them lowercase.

Also, everywhere but this list, Non-factored load has a hyphen, so I'll make that change too

---

Should I check is this is in Drasil too? @smiths

**Comment by smiths** [comment]
Sounds like a great plan.  Yes, please make the changes in Drasil too.  As trivial as it is, in the future Drasil should prevent us from having to worry about these kind of consistencies.  @szymczdm, this might be a point that you can make in your journal paper?  Even better, if we decide to change the style of capitalization, this is something we will eventually be able to specify.

**Comment by samm82** [comment]
The list of outputs is consistent (with the exception of Aspect Ratio) in Drasil @smiths, but it has a different list of outputs. Should I close this and make a new issue there?

## caseStudies List
Probability of breakage (Pb)
_**Risk of failure (B)**_
Load resistance (LR)
Applied load (demand) (q)
Stress distribution factor (J) - different location in Drasil
Non-factored load (NFL)
Dimensionless load (q̂)
Tolerable load (q̂tol)
Stress distribution factor based on Pb (Jtol)

## Drasil List

Probability of breakage (Pb)
Load resistance (LR)
Applied load (demand) (q)
Non-factored load (NFL)
_**Glass type factor (GTF)**_
Dimensionless load (q̂)
Tolerable load (q̂tol) 
Stress distribution factor (Function) based on Pbtol (Jtol)
Stress distribution factor (Function) (J)
_**Actual thickness (h)
Aspect Ratio (AR)**_

**Comment by smiths** [comment]
@samm82, I believe there is already an issue for this:

https://github.com/JacquesCarette/Drasil/issues/785

I didn't get into the details, but the point of the issue is to update the Drasil SRS to match the revisions to the manual version.  The revisions include the changes you have mentioned.

**Comment by samm82** [comment]
You're right - didn't make the correlation here. This issue can be closed then.
