### ISSUE TITLE
TSD/TDS mixup in MIS and minor typo?

### ISSUE THREAD

**Issue by niazim3** [smiths/caseStudies#110]
In the comment under the control module's exported constants, "TSD" is referred to as "TDS"
https://github.com/smiths/caseStudies/blob/75f88389777a2b76422e691ef34065f505ad411f/CaseStudies/glass/docs/Design/MIS/glassbr_mis.tex#L135
by accident; everywhere else it is referred to as "TSD".

**Comment by niazim3** [comment]
Also, "singelton" 
https://github.com/smiths/caseStudies/blob/75f88389777a2b76422e691ef34065f505ad411f/CaseStudies/glass/docs/Design/MIS/glassbr_mis.tex#L193
should be "singleton".

**Comment by smiths** [comment]
@niazim3 can you please fix these mistakes.  Thank you for noticing them.
