### ISSUE TITLE
Wording updates in NoPCM Assumptions

### ISSUE THREAD

**Issue by niazim3** [smiths/caseStudies#113]
Upon comparing the NoPCM's list of assumptions for JacquesCarette/Drasil/issues/843, I noticed the following discrepancies seem like quick fixes:

1. Drasil generates "... between the **heating** coil and the water", whereas the manual version has
![image](https://user-images.githubusercontent.com/28247301/42600396-1e3459be-8530-11e8-950c-50c2a7ee410f.png)

2. Drasil generates "... is always in liquid **_state_**...", whereas the manual version has
![image](https://user-images.githubusercontent.com/28247301/42600503-911e2874-8530-11e8-8d93-8e86e7ca4235.png)

@smiths, is it alright for the wording in Drasil to be propagated to this repo?

**Comment by smiths** [comment]
@niazim3 thank you for noticing these differences.  I agree that the Drasil wording is better.  @elwazana, it would be great if you could propagate these changes.

**Comment by niazim3** [comment]
Found one more discrepancy upon inserting missing assumptions into Drasil:

Drasil generates "... volumetric heat generation **per unit volume** is zero..." whereas the manual version has ![image](https://user-images.githubusercontent.com/28247301/42640145-aa448ac0-85bf-11e8-8dcc-9f9f4c166f60.png)

**Comment by elwazana** [comment]
@smiths Is the change @niazim3 mentioned approved for propagation?

**Comment by smiths** [comment]
Yes, please proceed.
