### ISSUE TITLE
Wording updates in MIS

### ISSUE THREAD

**Issue by niazim3** [smiths/caseStudies#114]
1. Should the following instead say something to the effect of "... in **the** program GlassBR" or "... in a program **called** GlassBR"?  ![image](https://user-images.githubusercontent.com/28247301/42645733-cbbc1bfc-85cc-11e8-978e-782c5f1d871a.png)
***
2. Use of the `\progname` command results in no spaces between the following words: ![image](https://user-images.githubusercontent.com/28247301/42645766-e2a07160-85cc-11e8-9412-002069a3b6d5.png)
***
3. Under the "MIS of FunctADT Module" section, should the following say "right **at** the edge" or "right **to** the edge" instead? ![image](https://user-images.githubusercontent.com/28247301/42645872-29a1296a-85cd-11e8-99c2-a9ed1dded403.png)

**Comment by smiths** [comment]
Thank you for the feedback @niazim3.  I agree with all of your points.  If you could make the fixes, that would be great, or reassign to someone else.  The specific fixes are as follows:

- "... in the program GlassBR"
- I believe \progname{} will leave a space (if not there is some other way to do this in LaTeX)
- "right to the edge"

**Comment by smiths** [comment]
Looks good.
