### ISSUE TITLE
Standardize to GlassBR in MIS and MG

### ISSUE THREAD

**Issue by samm82** [smiths/caseStudies#116]
Previously (JacquesCarette/Drasil#819), we decided to standardize to "GlassBR" and not use "Glass-BR". This should be done throughout the MIS (shown) and MG.

Example:
![glass-br](https://user-images.githubusercontent.com/35857611/42953636-e43d83ec-8b48-11e8-80ef-4bcbab37db1b.png)

**Comment by smiths** [comment]
Agreed.

**Comment by samm82** [comment]
@smiths Should this be done via a `\progname{}` as in the SRS or manually?

**Comment by smiths** [comment]
Yes, please use \progname{} in the MIS and the MG.  The MG is up to date.  The design given in the MG matches the MIS for GlassBR.
