### ISSUE TITLE
Consistency in 5.4.4 of MIS

### ISSUE THREAD

**Issue by samm82** [smiths/caseStudies#117]
In Section 5.4.4, under `verify_params()`, the following (arbitrary?) changes could be made to the list of exceptions to increase consistency:

- [x] Remove the word "dimension" as highlighted to match other constraints on _a_ and _b_
- [x] Change applicable highlighted regions to "greater than or equal to" (or something else?)
- [x] Make "Allowable" lowercase to match rest of list
- [x] Change "lie" to "be" to match rest of list
- [x] Put _w_ in parentheses to match format followed by stand off distance

![verify_params](https://user-images.githubusercontent.com/35857611/42954551-046dceb8-8b4b-11e8-8390-f0f86926897b.png)

**Comment by smiths** [comment]
Sounds great.  Please proceed.
