### ISSUE TITLE
Missing Commas in 6.4.5 of MIS

### ISSUE THREAD

**Issue by samm82** [smiths/caseStudies#119]
In Section 6.4.5 Access Routine Semantics, there should be a comma in the highlighted location in `output` for both `LoadTSD(s)` and `LoadSDF(s)` (shown).

![loadSDF](https://user-images.githubusercontent.com/35857611/42955588-d5af1b8a-8b4b-11e8-9055-3fc4b561ed8a.png)

**Comment by smiths** [comment]
Yes, please proceed with this change.
