### ISSUE TITLE
Capitalization in minx and maxx in 10.4 of MIS

### ISSUE THREAD

**Issue by samm82** [smiths/caseStudies#121]
In Section 10.4 Semantics, `minx` and `maxx` could be renamed to `minX` and `maxX` to:
- match `minD()` and `maxD()`
- solidify that `maxx` isn't a typo

This change should be made in 10.4.1 and 10.4.4 (partially shown)

![minx and maxx](https://user-images.githubusercontent.com/35857611/42956160-43030f88-8b4d-11e8-8d1d-41fcc65217dc.png)

**Comment by smiths** [comment]
@samm82, good suggestion and reasoning.  Please make this change.
