### ISSUE TITLE
Scientific Notation in 14.3.1 of MIS

### ISSUE THREAD

**Issue by samm82** [smiths/caseStudies#122]
In Section 14.3.1 Exported Constants, and as per JacquesCarette/Drasil#886, there should be explicit scientific notation where highlighted.

![sci not](https://user-images.githubusercontent.com/35857611/42956551-3d9b8812-8b4e-11e8-9d38-a356a623f6ed.png)

**Comment by smiths** [comment]
You mean that the multiplication symbol should be added?  That would be fine, but the current version was copied out of the SRS.  I was trying to keep them consistent.

**Comment by samm82** [comment]
Since the end goal is to have the multiplication symbol in the Drasil SRS, I think we should change this, especially as it has been added to the manual SRS

**Comment by smiths** [comment]
Okay, go ahead an add the multiplication symbol to the MIS.  I do prefer it being there.  It may be a bit before Drasil will match the case study version.

**Comment by smiths** [comment]
We are hoping to discuss multiplication in our "all hands" meeting tomorrow (July 24).  @szymczdm will be creating an issue describing how the printer will be changed in Drasil to automate the use of the multiplication symbol between constants and variables, and for displaying large and small literals.
