### ISSUE TITLE
Clarify module mentions in GlassBR MIS

### ISSUE THREAD

**Issue by niazim3** [smiths/caseStudies#125]
Under the MIS of Control Module's "Access Routine Semantics" section, it's stated: 
https://github.com/smiths/caseStudies/blob/71fd801e7c88d4ab7bf06da62eb6d79a9a1c0d2c/CaseStudies/glass/docs/Design/MIS/glassbr_mis.tex#L163-L164.

There are no modules that are named `Param` or `Plot` in the MIS, which makes it unclear whether these are synonyms for the names of other modules or if modules are missing...

**Comment by smiths** [comment]
You are correct @niazim3.  I have updated the blurb to only refer to modules that exist.  I've also added state variables to the control module, since they were implied previously by the calculations, but not actually listed.  The changes are made in commit fb4b20a.
