### ISSUE TITLE
Missing inputs? (MIS Review)

### ISSUE THREAD

**Issue by elwazana** [smiths/caseStudies#127]
@smiths Hello Dr. Smith, I am reviewing the MIS document and I found this. I'm not sure if this is an error or if this is how it should be;

calc_LR seems to only take NFL as input:
![image](https://user-images.githubusercontent.com/35268928/43008741-cf49191c-8c09-11e8-8998-d4006527e226.png)

But then it is calculated with GTF and LSF:
![image](https://user-images.githubusercontent.com/35268928/43008707-ba9d09ec-8c09-11e8-98b7-23cb9c3ef6c9.png)

The Drasil side also has GTF and LSF listed as inputs for LR:
![image](https://user-images.githubusercontent.com/35268928/43008958-681cb0fe-8c0a-11e8-918b-668aba6fda3d.png)

Should GTF and LSF be in the inputs list for calc_LR?

**Comment by smiths** [comment]
The variables that you highlighted are defined through the import of the Input module.  We could quality them with Input.GTF etc, but then the equation doesn't look like it does in the SRS.  We could also add notation to the import to say something like

Uses

GTF, LSF from Input (Section 5)

The problem with this is that we are using many of the parameters from Input and listing them all would be distracting.  We could have a notation like Uses * from Input, but as it is, the default is to import everything, which should be fine.

I don't think there is a problem here, but if you have other ideas, please let me know.
