### ISSUE TITLE
Disordered Table Section 5 (MIS)

### ISSUE THREAD

**Issue by elwazana** [smiths/caseStudies#128]
@smiths The table in Section 5.3 Syntax seems to be disordered:
![image](https://user-images.githubusercontent.com/35268928/43009441-b569d94e-8c0b-11e8-910b-cb965bc36dfa.png)

But according to Section 5.4.3 Assumptions:
![image](https://user-images.githubusercontent.com/35268928/43009525-f4e1cf3c-8c0b-11e8-932e-04cd0548a5ea.png)

The correct order should be:
![image](https://user-images.githubusercontent.com/35268928/43009624-2df569be-8c0c-11e8-894e-c0e91aa3fea0.png)

**Comment by smiths** [comment]
Please correct this.  The original table was literally copied from the SRS.  The order should be the same.  I guess the order of the table was changed after I copied the information.  This is why copy and paste is bad for maintenance!  We need Drasil to be working for all artifacts.

**Comment by elwazana** [comment]
@smiths Hello Dr. Smith, I've corrected the order of the table above here are the changes and commit: 856182f1fa8908b3cef96d84269d0d019db72630
![image](https://user-images.githubusercontent.com/35268928/43088328-e57beefe-8e6f-11e8-8f49-ea02b085d52b.png)

**Comment by smiths** [comment]
Great.
