### ISSUE TITLE
Naming `FunctADT` Module in MIS 

### ISSUE THREAD

**Issue by niazim3** [smiths/caseStudies#131]
Is there a reason why this module is named what it is? 
Can it be named to something more descriptive? Would `InterpADT` be a poor choice?
![image](https://user-images.githubusercontent.com/28247301/43012282-f01f160a-8c13-11e8-90d8-5f89d5159363.png)

**Comment by smiths** [comment]
I like the name.  The ADT represents a function.  For any value of x it returns a value of the function.  It stores the limits over which the function is defined.  It uses interpolation, but it could use regression or some other approach and have almost the same interface.  I thought about the name curve, but that is more general than we want to be.  A curve isn't necessarily a function.  I'm happy to listen to other ideas, but for now I'm going to close this issue.
