### ISSUE TITLE
SI units correction

### ISSUE THREAD

**Issue by elwazana** [smiths/caseStudies#132]
As discussed in https://github.com/JacquesCarette/Drasil/issues/824, there are serious of symbols that need to convert from (mm -> m) and (kPa -> Pa). These changes need to be done in tables and in the equations which currently have a conversion factor.

Example:
![](https://user-images.githubusercontent.com/35268928/42636295-6a792742-85b6-11e8-9e6d-fe33b4c60da3.png)

This issue is specific to keep track of the changes to the manual documentation.

**Comment by elwazana** [comment]
These are the fixes so far, all of which are located here:
40f50e82c46e704625f87851262d06c43f615fb1
![image](https://user-images.githubusercontent.com/35268928/43142194-d4d83e70-8f25-11e8-8425-dd23552c6434.png)
@smiths Should `d`<sub>`max\min`</sub> be converted to `m` as well?

Removed the conversion factors:
![image](https://user-images.githubusercontent.com/35268928/43142243-f303da1c-8f25-11e8-976a-d2a1d71d2bac.png)
![image](https://user-images.githubusercontent.com/35268928/43142468-75c27d50-8f26-11e8-9514-1d8199a4d8d8.png)

Typical value fix (Used to be 1500 mm and 1200 mm):
![image](https://user-images.githubusercontent.com/35268928/43142518-9693744e-8f26-11e8-9a00-6c9294563479.png)

**Comment by smiths** [comment]
Yes dmin and dmax should be converted to m.

**Comment by elwazana** [comment]
This is the only place where `dmax` and `dmin` were written as `mm`:
3a4e75a1950a4876aae88b0ad5f1950003b4390a
![image](https://user-images.githubusercontent.com/35268928/43143129-0f0783c4-8f28-11e8-8328-33605c33d01e.png)

I've also noticed and fixed a unit conversion for `a` and `b` that I missed before:
![image](https://user-images.githubusercontent.com/35268928/43143390-aaffcb1a-8f28-11e8-931e-c0c2aa0e5edf.png)

**Comment by smiths** [comment]
Looks good.  Can you search the document for instances of kPa as well?  kPa should be changed to Pa, except for in Figure 7.

**Comment by elwazana** [comment]
Occurrences of kPa:
![image](https://user-images.githubusercontent.com/35268928/43143859-d1eaaf78-8f29-11e8-964b-52fffa877911.png)
![image](https://user-images.githubusercontent.com/35268928/43143937-fcf5a646-8f29-11e8-8c17-0ac304c25272.png)

Fixed here:
7865849ee868085747bf74efde426b24ffd008b1
![image](https://user-images.githubusercontent.com/35268928/43144229-96ee3c36-8f2a-11e8-9d59-871ec2167753.png)
![image](https://user-images.githubusercontent.com/35268928/43144192-861be8e0-8f2a-11e8-8a69-47497b49ec88.png)

**Comment by smiths** [comment]
Great!
