### ISSUE TITLE
State Variables in 5.4 State Variables in GlassBR MIS

### ISSUE THREAD

**Issue by samm82** [smiths/caseStudies#135]
The State Variables are listed as so (_a_ to _t_):

<img src="https://user-images.githubusercontent.com/35857611/43163335-d2840ace-8f5b-11e8-98cf-41e3d0c63ffe.png" width="250">

But the specification for `load_params(s)` says "(_a_ to _w_)," which implies that the State Variables list is sorted alphabetically.

<img src="https://user-images.githubusercontent.com/35857611/43163381-f4ce6ab6-8f5b-11e8-95ce-3cc9503762b3.png" width="550">

Should the list be sorted alphabetically, or should the procedure for `load_params(s)` be changed to "(_a_ to _t_)?

**Comment by smiths** [comment]
I would like the list in the same order as the SRS, R1.  We should remove the text (a to w).  It isn't necessary, and it will be difficult to maintain manually.  Can you please look at the SRS and modify the MIS state variable order, if necessary.

**Comment by samm82** [comment]
I'm going to assume the same change should be made for the list from SRS R2
