### ISSUE TITLE
Data Constraints AR row

### ISSUE THREAD

**Issue by elwazana** [smiths/caseStudies#136]
As discussed in issue #129, AR will be getting its own row in the InputDataConstraints table. Instead of being weaved into `a` and `b`'s rows.

Current Manual:
![](https://user-images.githubusercontent.com/35268928/43163402-0c195d70-8f5c-11e8-91e6-a8a796621750.png)

**Comment by smiths** [comment]
Good.  #137 is also related to this constraint.

**Comment by elwazana** [comment]
Intial occurence of `AR` in the Data Constraints:
![image](https://user-images.githubusercontent.com/35268928/43264736-e93e4b26-90b4-11e8-9ee5-579c2668a629.png)

Newly modified table:
![image](https://user-images.githubusercontent.com/35268928/43264885-475b4b3c-90b5-11e8-8846-2fbd594d8b50.png)

These changes are to the SRS document of GlassBR and they can be found here:
ef855ec3c8e70be006704b02daaa6de0b05d5255

**Comment by smiths** [comment]
Looks good.  A minor suggestion is to move AR after a and b in the table.  I think it would look better.  (I think that change would also match an alphabetical listing that is case sensitive, with lower case first.)

**Comment by elwazana** [comment]
@smiths In Drasil the table is ordered alphabetically with case sensitive in mind, however, that just means `a` goes before `A` not `b` goes before `A`; this means the case sensitivity is per letter not per table. Also if we made the tables order lower case first before capitalization for every letter, then `w` would be bumped up here.

Drasil:
![image](https://user-images.githubusercontent.com/35268928/43270902-2e030b70-90c4-11e8-88b4-369a304f99bf.png)

**Comment by smiths** [comment]
Okay. Makes sense.
