### ISSUE TITLE
FileError not Predefined

### ISSUE THREAD

**Issue by samm82** [smiths/caseStudies#138]
Unless I'm misunderstanding this and you want errors to be raised by:
```python
raise SystemExit("ValueError: TNT must be positive")
```
(as used in previous implementation) as opposed to:
```python
raise ValueError("TNT must be positive")
```
the highlighted error should actually be a `FileNotFoundError` (and as a bonus would trigger without us explicitly `raise`ing it), as `FileError` is not a predefined exception.

![fileError](https://user-images.githubusercontent.com/35857611/43214060-335d29fc-9006-11e8-8b7d-9faa110f4873.png)

---
If you want exceptions `raise`d the old way, the exceptions listed should both be `SystemExit`.

**Comment by smiths** [comment]
The MIS is actually intended to be language agnostic.  Sometimes this is relaxed to make life a bit easier, but we really should be able to generate any language code from the MIS.  In some cases this means defining a mapping between the MIS and the specific language.  For instance, renaming FileError.  We don't need to change the error in the specification.  Whatever equivalent name in the implementation language is fine.

We should be using ValueErrors, not SystemExit.  I don't agree with the previous implementation on this.  We want an error that can be trapped and handled.  We haven't thought much about exception handling, but we want to leave the possibility open.

**Comment by samm82** [comment]
Thanks for the clarification! This issue can be closed then.
