### ISSUE TITLE
Nominal Thickness Units?

### ISSUE THREAD

**Issue by elwazana** [smiths/caseStudies#139]
@smiths Hello Dr. Smith, I noticed this:
![image](https://user-images.githubusercontent.com/35268928/43272977-4464e58c-90c9-11e8-8f0e-ece3a76015bc.png)
In Drasil and Manual. 

It seems like we missed it in our discussion on which units each symbol should be in. I've tried looking at the source material to see if I could find anything there like I found with `a`, `b`, and `h` but I couldn't find anything. Should nominal thickness be kept as `mm`?

**Comment by smiths** [comment]
Yes, t should be in mm.  It isn't "real" in the sense that t isn't used in any equations.  The designation for a certain thickness of glass is "2.5 mm".
