### ISSUE TITLE
Minimum (h) Thickness conversion from mm to M

### ISSUE THREAD

**Issue by elwazana** [smiths/caseStudies#140]
@smiths Hello Dr. Smith, I missed this when I was converting symbols from mm to m and am creating this issue to keep track of it.

`h` was changed from mm to m, however, the actual values weren't. So I'm pretty sure these values:
Drasil:
![image](https://user-images.githubusercontent.com/35268928/43273861-9810b8da-90cb-11e8-8c42-7ee97af80c95.png)
need to be [0.00216, 0.00259, .  .  . ]. This problem also appears in the manual. 

It also appears in the MIS:
![image](https://user-images.githubusercontent.com/35268928/43274266-b88980e6-90cc-11e8-8af0-063e77467899.png)

This issue is related ti issue #139, as the Minimum Thickness is calculated based on the Nominal Thickness.

**Comment by smiths** [comment]
@elwazana, I think you might have missed the factor of 1/1000 in front of the equation.  For h this is a better way to write it.  I don't know the issue number, but we discussed this long ago (before your time).  We should use the same notation in the case study SRS and in the MIS.

I'm glad to see that you have left t in mm.  t is just a "label" for the different thicknesses of glass.  It doesn't really have units in the sense that it never appears in any equations directly.

**Comment by elwazana** [comment]
SRS updated:
bb6bd8e43e44a92db7c30a4fcc75796f288484e4
![image](https://user-images.githubusercontent.com/35268928/43284661-8426cd36-90ea-11e8-9333-b6007126be3b.png)

MIS update:
4a28219317875fe0f3602d9dc42319e6083ec732
![image](https://user-images.githubusercontent.com/35268928/43284977-8dfe3708-90eb-11e8-87d4-23a2658f2851.png)

**Comment by smiths** [comment]
In the MIS version, please remove the "h = " part.  out has the role of taking the output as defined by the equation.  h doesn't actually have any meaning here.

**Comment by elwazana** [comment]
Here is the fix:
c429853565b151acef666a4ac65648d80f8cc8d5
![image](https://user-images.githubusercontent.com/35268928/43286782-0b513674-90f1-11e8-8042-aea89d99b9e7.png)

**Comment by smiths** [comment]
looks good.
