### ISSUE TITLE
Reference Section Misplacement in GlassBR MIS

### ISSUE THREAD

**Issue by samm82** [smiths/caseStudies#142]
The references section in the MIS comes after the Module Hierarchy instead of at the end of the document and doesn't show up in the table of contents.

![refs](https://user-images.githubusercontent.com/35857611/43796796-3ec3ed92-9a53-11e8-8cfe-89a7be911f28.png)

**Comment by smiths** [comment]
Different choices could certainly be made here, but I don't think what is currently done with the references is incorrect.  The actual specifications are like an appendix to the document.  The references apply for the "front-matter", so they are given at the beginning.  The absence of a section number for the References section is the default LaTeX behaviour; I don't think we need to override that default.
