### ISSUE TITLE
Review GlassBR ProblemStatement

### ISSUE THREAD

**Issue by vajihehm** [smiths/caseStudies#147]

**Comment by smiths** [comment]
Some tex writing issues are identified in issue #148.  With respect to the actual content, I would like you to simplify it.  The spontaneous failure of windows is certainly a real concern, but it doesn't have anything to do with GlassBR.  You can make it simpler and just refer to the problem that GlassBR addresses.

I don't think GlassBR has anything to do with safety glazing.  You can remove that material.  We should just focus on the safety issues for windows failing under a blast load.

**Comment by vajihehm** [comment]
@smiths Thank you for your review.I would grateful if you please introduce me a GlassBR document which help me about content of ProblemStatement and SRS(requirements) as well.

**Comment by smiths** [comment]
@vajihehm I'm not sure I understand your question.  Everything you need is in the case studies repo.  The existing SRS should be enough to write your problem statement.  You might be thinking too much.  It will be quite short and simple.  Maybe you mean the reference documents that GlassBR is based on?  You'll find them at:

https://github.com/smiths/caseStudies/tree/master/CaseStudies/glass/refs

**Comment by smiths** [comment]
Problem statement approved.
