### ISSUE TITLE
Changes to LaTeX for Problem Statement

### ISSUE THREAD

**Issue by smiths** [smiths/caseStudies#150]
@oluowoj, thank  you for submitting the problem statement for GlassBR in issue #149.  To help me review your work, can you please do the following:

- [x] add the Comments.tex file to the tex file and to the repo, so that I can add comments
- [x] use an editor that has a hard wrap at a text width of 80 characters
- [x] please edit the file so that there is correct spacing for punctuation

As you complete these items you can tick them off above.  When they are all complete you can close the issue.  When closing the issue, please include the commit number that addresses the above points.

Similar comments were made for GlassBR: #148.

**Comment by oluowoj** [comment]
commit number : 6144006 
Hello Dr. Smith, 
I have addressed the points in the ticket. Please take a look.

**Comment by oluowoj** [comment]
I will close the ticket when you are satisfied with the fixes. Thanks

**Comment by smiths** [comment]
I pointed out some further problems with the spacing around punctuation, but I'll trust that you'll make those fixes and I can close this issue.  I'll update the Repos.xls file to show your project has been approved.
