### ISSUE TITLE
SRS Completeness in the Different Sections

### ISSUE THREAD

**Issue by vajihehm** [smiths/caseStudies#161]
1- (mostly minor issue)  In the section “Organization of Document” it should be referred to the goal statement “5.1.3”.

2- In the System context section in the SSP Responsibilities It should be added physical and **data constraints** (by referred to the section) because system should satisfy data constraints as well.

3- (Mostly minor issue) Section 5.1.1 should be changed to the “Terminology and Difinition”.

**Comment by bmaclach** [comment]
Items 1 and 2 addressed in c2afed2d8d0bcdb1560c65a7b997c89a3a12c02e.

As for item 3, we should ask @smiths about this since it would be a change to the template.

**Comment by bmaclach** [comment]
My apologies, @vajihehm and @smiths, I realize now that the heading in the template was indeed "Terminology and Definitions". I fixed this in 17e79f21e4cfa043dc7d87191ba9ffda250af082 and will close this issue once that gets merged into master.

**Comment by vajihehm** [comment]
@bmaclach Thank you Brooks. I reviewed SRS again. So, I think we can close this issue after making the changes into the master branch.
