### ISSUE TITLE
SRS Review: GlassBR Scope

### ISSUE THREAD

**Issue by oluowoj** [smiths/caseStudies#174]
<img width="654" alt="image" src="https://user-images.githubusercontent.com/43192745/46846778-2b0c5700-cdaf-11e8-8227-0de389c7b17d.png">

The second statement has a bit of repetitions when it refers to input, maybe remove the 1st part of sentence 2 and merge the second part of statement 2 to statement 1. e.g 

<img width="656" alt="image" src="https://user-images.githubusercontent.com/43192745/46847079-87bc4180-cdb0-11e8-9154-01771fb2aa3b.png">

**Comment by vajihehm** [comment]
@oluowoj it was fixed with 9851355.

**Comment by smiths** [comment]
Issue was fixed as noted above.
