### ISSUE TITLE
SRS Review(GlassBR) - Problem Statement

### ISSUE THREAD

**Issue by oluowoj** [smiths/caseStudies#177]
Problem Description: If possible, rephrase the statement in problem description.

<img width="639" alt="image" src="https://user-images.githubusercontent.com/43192745/46847836-76753400-cdb4-11e8-847e-1c31558e6107.png">

**Comment by oluowoj** [comment]
*** that predict not predicts

**Comment by vajihehm** [comment]
@oluowoj with respect to your opinion, "predict" refers to "outputs" not "GlassBR", So, it should be "predict" not "predicts".

**Comment by smiths** [comment]
The current version of GlassBR is now maintained in the Drasil repo (https://github.com/JacquesCarette/Drasil).  The problem description in that repo improves on what is currently in this repo, so this issue can be closed.
