### ISSUE TITLE
Gamephy SysVnVplan ready for review

### ISSUE THREAD

**Issue by oluowoj** [smiths/caseStudies#180]
SystemVnVPlan for Gamephys is ready for review. I apologize for the delay.

https://github.com/smiths/caseStudies/tree/gamephy_SysVnVPlan/CaseStudies/gamephys/docs/VnVPlan/SystVnVPlan

**Comment by oluowoj** [comment]
@karolserkis please see link in the above thread for SystemVnVplan location

**Comment by smiths** [comment]
Hello @oluowoj.  I have commented on your VnV plan at:

https://github.com/smiths/caseStudies/commit/5a61c56dce95dbe0b43a28b8044e812437644b95

**Comment by smiths** [comment]
I added one more comment on the VnV plan in 4b0033b.
