### ISSUE TITLE
SSP_SystemVnVPlan review #1

### ISSUE THREAD

**Issue by oluowoj** [smiths/caseStudies#181]
@bmaclach, this is just a clarification that I require for the valid input of your testcases:

Is there a range for the valid input values listed in (see arrow in screen shot or could they be any value except the ones you listed in the invalid input table?

<img width="583" alt="image" src="https://user-images.githubusercontent.com/43192745/47598922-9d656580-d971-11e8-8aae-ec188a209fbe.png">

**Comment by bmaclach** [comment]
The constraints for these inputs are not really ranges on the values but rather restrictions on how the values relate to each other. For example, the y-values must be always increasing or always decreasing, but cannot increase at one part of the slope and decrease at another.

I've tried to create one test case for each possible violation of the input constraints, and one test case for each possible valid input scenario on a high level. So, for example, I have valid input test cases for the increasing scenario and for the decreasing scenario, but only one test case for each. I felt that adding more test cases to cover different input values following the same (increasing or decreasing) pattern would be testing almost the exact same thing, and so those test cases would not be valuable. 

Does this answer your question, @oluowoj?

**Comment by oluowoj** [comment]
Yes, thanks, ticket can now be closed.
