### ISSUE TITLE
SSP_SystemVnVPlan - #2

### ISSUE THREAD

**Issue by oluowoj** [smiths/caseStudies#182]
Would this be considered invalid input. This TC is from the Valid input section

<img width="572" alt="image" src="https://user-images.githubusercontent.com/43192745/47599014-46609000-d973-11e8-833d-15e509024123.png">

If this is considered invalid input, is this listed as an invalid input or is there a similar input in the invalid input section that covers for this. If its not an invalid input, maybe you can state why not to use this value. Just looking at this from a tester's point of view.

**Comment by bmaclach** [comment]
I don't quite understand your question. This is valid input, but maybe my phrasing has caused some confusion, in which case I will make an edit to rephrase the test case. Can you be more specific as to why this seems like invalid input, @oluowoj?

**Comment by oluowoj** [comment]
Please disregard this, I think it was a lack of understanding at that time, but its clear to me now reviewing you unit VnV as well.
