### ISSUE TITLE
SSP_SystemVnV Review - #3

### ISSUE THREAD

**Issue by oluowoj** [smiths/caseStudies#183]
<img width="571" alt="image" src="https://user-images.githubusercontent.com/43192745/47599130-39dd3700-d975-11e8-9b84-069950cb4888.png">
I think its still better to explicitly have a testcase for Correctness in your NFR testing section even though it has been addressed in the Functional Reqt. testing. You can just reference the section and state that if the TCs in sections..... pass then the software passes for Correctness...just something in that line, I hope you get what I mean. This is just my thought.
@smiths what do you think?

**Comment by smiths** [comment]
I like the idea from @oluowoj.  You don't want to write new tests cases in the correctness NFR section, but you can reference functional tests from the other sections.

**Comment by bmaclach** [comment]
I've addressed this in 1243827761aba2666146b79e5c99522e55ca5496. This issue will be closed when the ssp_SystVnVPlan branch gets merged into master.
