### ISSUE TITLE
GlassBRVnVPlan to Review

### ISSUE THREAD

**Issue by vajihehm** [smiths/caseStudies#196]

**Comment by vajihehm** [comment]
@smiths I am writing to let you know my VnVplan revisions are on the glass_revisions branch, not on master. I do not know Karol github ID to assign for review. Thanks.

**Comment by smiths** [comment]
Thank you.

@vajihehm,  you can find Karol's github id by looking at his project.  I believe you can get this message to him by referencing his id: @karolserkis.  To be on the safe side, I'll forward your message to him.

**Comment by vajihehm** [comment]
@smiths Thank you.
 @karolserkis my VnVPlan is ready to review. Thank you.

**Comment by karolserkis** [comment]
Thanks, I will take a look now and review it: @vajihehm @smiths

**Comment by karolserkis** [comment]
I just realized the Repos.xlsx doesn't have @vajihehm assigned to me instead it has @whitere? @smiths was there a mistake made in Repos.xlsx

**Comment by smiths** [comment]
@karolserkis, you are inverting the interpretation of the Repos.xlsx spreadsheet.  Cell G5 indicates the name of who reviews the VnV plan for @vajihehm and that cell contains your name.  😄

**Comment by smiths** [comment]
@vajihehm I have completed the review of your VnV plan in commit df9d513.

**Comment by vajihehm** [comment]
@smiths Thank you. I will make changes on it based on your feedback ASAP.

**Comment by smiths** [comment]
Great!
