### ISSUE TITLE
Game Physics: Missing Characteristics of Intended Reader section in manual version.

### ISSUE THREAD

**Issue by deviprasad135** [smiths/caseStudies#2]
There is no Characteristics of Intended Reader section in manual.

**Comment by smiths** [comment]
Add this section to the manual version.

**Comment by deviprasad135** [comment]
Section Characteristics of Intended Reader is added to manual version. Commit fc25f61

**Comment by smiths** [comment]
Hello @deviprasad135.  This is a much better way to report your work.  I (and anyone else) can easily review your changes.  For the rigid body dynamics, please say that the knowledge would be at the level covered in a second year engineering mechanics course.  For the calculus background, I suggest changing the requirement to Calculus 1 (First year engineering or science Calculus).

**Comment by deviprasad135** [comment]
Modified according to the comment mentioned above. Commit aaea317

**Comment by smiths** [comment]
We could make the English flow a little better, but you have captured the main idea.  We'll close this issue.
