### ISSUE TITLE
Rearrange Reference Information for Assumptions

### ISSUE THREAD

**Issue by halonazhao** [smiths/caseStudies#201]
Hello Dr. @smiths,
I have made changes for Nopcm case. 0da674f39c46c4c2e94e0b4adc63e2a702b54a82 Could you review those changes and give some suggestions?
And then I will propagate the changes to other cases.

- [ ] SWHS

- [ ] GlassBR

- [ ]  SSP

- [ ] GamePhysics

**Comment by JacquesCarette** [comment]
Thanks for cross-referencing. I don't think this change, however, is the right way to go.  I think the case studies should not be changed (for now). Yes, Drasil-stable and the case studies will diverge, but hopefully just for a short while, as things are re-arranged. The information should *come back* (in Drasil-stable) once we can reliably to 'ref by' automatically.  I think that @halonazhao has already implemented the core technology to do it, but it will need to be plugged in to docLang, and that has not been done.
