### ISSUE TITLE
Correct SRS for GlassBR, especially for TM, DD and IM

### ISSUE THREAD

**Issue by smiths** [smiths/caseStudies#202]
Please correct the SRS following the comments given in 7af0788.

The most significant change is to move the existing TMs to be IMs and to move the existing IMs to DDs.  You also need to add two new TMs, as described in the document.  (This is all in branch glass_revisions).

@halonazhao, @bmaclach and @JacquesCarette, the proposed changes will be of interest to you as well.  I made the changes to follow the explicit dependency we came up with between TM, GD, IM, DDs and As.  The existing TMs were referencing IMs, which they shouldn't do, since IMs are supposed to be a refinement of the TMs.  

This way of thinking naturally shows that the existing TMs were far too specific.  They aren't reusable in another context.  The newly proposed TMs will be more abstract.  They should apply in other contexts.  In particular, the theoretical model for safety should be that the capacity is greater than the load.  This "law" applies to glass, but it also applies to slope stability.  The slope is stable if the shear resistance is greater than the applied shear.

**Comment by vajihehm** [comment]
@smiths Hello Dr.Smith. Most of changes have been done with  d82cd4e. I have added my comments in the document. So, I think it is good idea to get started the review. "Traceability Matrices and Graphs" had major changes as initial version had have many problems. I have already done two of them. I will finish all of them ASAP to move to making changes on Drasil. I will pull request when all of my changes are done. Thanks.

**Comment by smiths** [comment]
@vajihehm, I have completed my review of your SRS.  I have made changes and added comments through several commits.  The last commit is 2e14e76.  You do not need to worry about the traceability graph at this time.  We can sort that out later.  It will be much easier once Drasil can automatically build these graphs.

@vajihehm, please address the questions that I have embedded in the tex file for the SRS.  You are also good to go for modifying Drasil to reflect the changes to the case study.  Please coordinate your efforts with @halonazhao, since she is very interested in breaking the cyclic imports.

**Comment by vajihehm** [comment]
@smiths Thank you. I will address your comments ASAP.
