### ISSUE TITLE
Revise Game Physics SRS

### ISSUE THREAD

**Issue by smiths** [smiths/caseStudies#203]
Please make the changes to the game physics SRS indicated in 7508a15.

@halonazhao and @JacquesCarette, some of these changes will interest you as well.  The reclassification of the GDs, TMs etc should mean that cross-referencing will not have any cycles.  The requirements as a whole should also make more sense now.

**Comment by oluowoj** [comment]
Thanks, I have reviewed your comments and will work on them.

**Comment by smiths** [comment]
Sounds good.  Please do not hesitate to ask questions.

**Comment by smiths** [comment]
I believe these revisions have been taken care of elsewhere, since the cyclic imports are now gone.
