### ISSUE TITLE
MG Review - ISSUE #2 - about modules

### ISSUE THREAD

**Issue by whitere123** [smiths/caseStudies#209]
Hello again @oluowoj , 

This issue is related to the modules in your MG. 

In 6.3.5 you should  begin by explaining the services abstractly and follow up with some specific examples (as you did with all the other services ). For example, "this module implements operations/algorithms for collisions, such as filtering etc.. " . I think that the overall document would read better this way, as you would be more consistent. 

Also, the modules are numerically mislabeled in your hierarchy.  For example, in figure 1 you have M10-spatial index and in 6.3.4 you have M12-spatial index.

**Comment by oluowoj** [comment]
@whitere123, section 6.3.5 has been simplified and your feedback has been added to the document with b48e710. section 6.3.4 M12 - Spatial Index has been removed, it will not be implemented.

Please let me know if ticket can be closed.

**Comment by whitere123** [comment]
@oluowoj , yes you can close the issue.
