### ISSUE TITLE
MG Review - ISSUE #3 - Arbiter

### ISSUE THREAD

**Issue by whitere123** [smiths/caseStudies#210]
Hello again @oluowoj , 

This issue is regarding your arbiter module. 

I think that you should provide a lot more detail in the secrets and services of the arbiter module. My current impression is that the arbiter module stores the initial input data AND output collision data that is received after all the initial data is processed by the other modules. This conflicts with my interpretation of your hierarchy diagram.  

These are all of my issues. Overall you did a really good job! :)  

PS: @smiths I am unable to create assignees ..

**Comment by oluowoj** [comment]
@whitere123, MG has been simplified a lot and the Arbiter Module will not be implemented, so I redid the diagram. You are right about the Arbiter Module but everything will now happen in Space Module.

Let me know if it is okay to close this ticket.

**Comment by oluowoj** [comment]
commit ID 0dd278f

**Comment by whitere123** [comment]
Hello @oluowoj , 
Closing this issue is fine with me.
