### ISSUE TITLE
MG Peer Review ISSUE #4 (section 9)

### ISSUE THREAD

**Issue by whitere123** [smiths/caseStudies#211]
hello again @oluowoj , 

This is more of a suggestion than an issue. I think it would be good to add a small blurb to section 9 of your document. Perhaps you could explain the inheritance of the different shapes, ie what elements are common between the different types of shapes? What are the subtle differences (why are there individual shape modules)?   I think that this would really add to the quality of your document.

**Comment by oluowoj** [comment]
@whitere123 I think this is more for the MIS and this will be stated in the MIS. I will expansiate more on the inheritance and the similarities and differences between those.
