### ISSUE TITLE
GlassBR MG to review

### ISSUE THREAD

**Issue by vajihehm** [smiths/caseStudies#212]
@smiths Sorry Dr.smith I had forgot to assign GlassBRMG to you for review. I have just assigned right now.

**Comment by smiths** [comment]
No problem @vajihehm.  I will review your MG as soon as I am able.

**Comment by smiths** [comment]
The comments on GlassBR MG are in 1fc41d0.  I'm afraid that I don't see the point of the changes you have suggested with respect to glass type.  

With respect to the MIS, you should definitely review the existing documentation, but the changes needed will likely be minimal.  For this reason, it is important that we finish up the edits to the SRS.  We really need you to start modifying the SRS in Drasil.

**Comment by vajihehm** [comment]
Hello Dr.Smith,

Thank you for your consideration. I am working on SRS. It will have done by tomorrow. I will push most of the changes this night. I read your comment, so I will review MIS for comment of Glass type and let you know if I have new comment.  Sorry for late submission. Configuration of new laptop took a couple time. 

Warm Regards,
Vajiheh
