### ISSUE TITLE
ssp-MG-guide - Review (AC and UC)

### ISSUE THREAD

**Issue by karolserkis** [smiths/caseStudies#215]
Hello, @bmaclach 

I apologize for the lateness of my issues. Perhaps they can be useful for the final submission at this point.

Section 4.1 and 4.2 the first anticipated change AC1 is relating to the specific hardware and the first unlikely change UC1 is also relating to the specific hardware. I haven't asked @smiths whether you can have the anticipated change and unlikely change be referencing the same thing in indecisiveness to whether, in your example, the system should or should not have more memory or different configuration, display, input/output etc.
It seems to make more sense to be more specific in AC1, perhaps? Just to avoid contradictory statements.

[MG.pdf]
(https://github.com/smiths/caseStudies/blob/master/CaseStudies/ssp/docs/Design/MG/MG.pdf)

**Comment by bmaclach** [comment]
Thanks @karolserkis, you are right that these seemed to contradict each other. I added some more explanation to make it more clear that the AC was referring to the specific hardware, whereas the UC was referring to features, like a keyboard or screen, that any hardware will have. This fix is here: 1b60e54b9916a7917bc1a07cd2bb796c7cfbca1b, and the issue will be closed when it is merged into master.
