### ISSUE TITLE
Punctuation for equations with cases

### ISSUE THREAD

**Issue by bmaclach** [smiths/caseStudies#216]
I noticed while revising SSP that when an equation has cases, there is sometimes a comma after each case but before the case predicate, as in DD4 below:
![image](https://user-images.githubusercontent.com/18634568/48922380-54230b80-ee74-11e8-9819-9588e41fccb3.png)

And sometimes there is no punctuation, as in IM3:
![image](https://user-images.githubusercontent.com/18634568/48922387-6604ae80-ee74-11e8-97a7-45d3689d8dee.png)

I want to make these consistent but do not know which format is better. @smiths do you have a preference for commas or no commas?

**Comment by smiths** [comment]
@bmaclach, I prefer it without the commas, but my preference isn't a strong one.  As  you have said, the most important thing is consistency.

**Comment by JacquesCarette** [comment]
Without the comma!

**Comment by bmaclach** [comment]
Thank you both! I'll remove the commas where they occur. Since this issue was intended as a question, I'll go ahead and close it.
