### ISSUE TITLE
Edit issue titles

### ISSUE THREAD

**Issue by smiths** [smiths/caseStudies#22]
Please make the titles for issues #1 to #19 more descriptive.

**Comment by deviprasad135** [comment]
I have changed the titles. Are they fine? @smiths

**Comment by smiths** [comment]
The issue titles are much improved, but we can still tweak them a bit to get them even more descriptive.  Please make the following changes:

1. Remove the text "issue regarding."  It makes the titles longer without adding any additional information.
2. Avoid identical issue titles.  Add something distinguishing, like the section number or other pointer, so that each issue title is unique.

**Comment by deviprasad135** [comment]
I have made the changes as you suggested. Are they fine Now? @smiths

**Comment by smiths** [comment]
Looks great.  Thank you @deviprasad135.
