### ISSUE TITLE
GamePhy UnitVnV

### ISSUE THREAD

**Issue by oluowoj** [smiths/caseStudies#234]
Hello Dr. Smith,

Please find UnitvnV for GamePhy here:
https://github.com/smiths/caseStudies/tree/gamephy_UnitVnV/CaseStudies/gamephys/docs/VnVPlan/UnitVnVPlan

**Comment by smiths** [comment]
Comments on the Unit VnV plan are given in 6984296.

**Comment by oluowoj** [comment]
Thanks @smith, I will add a few more test that I came up with while running my unit test. I will address your comments as well. Thanks

**Comment by smiths** [comment]
Great!
