### ISSUE TITLE
Elements in the Family of Lessons

### ISSUE THREAD

**Issue by smiths** [smiths/caseStudies#246]
I found some good sources on-line that have distilled the elements that typically appear in a textbook chapter.  They don't present this information as a commonality analysis of the family of textbooks, but it works nicely if you view their results from that perspective.

Pages 2 and 3 of this document summarize the family of textbook chapters:

https://github.com/smiths/caseStudies/blob/master/CaseStudies/projectile/projectileLesson/AboutProjectileLesson.pdf

I think we could use this list to categorize the knowledge in the textbook lesson for projectile.  This should help us build a general approach that we can use for other lessons.  This could also give us a language that we can use when comparing the projectile lesson to the SRS.

You can close this issue once you have a look over the link above.  I should also add Ting-Yu to this repo so that she can have a look.

**Comment by JacquesCarette** [comment]
This is indeed very valuable information. Good find!
