### ISSUE TITLE
Review GlassBR documentation

### ISSUE THREAD

**Issue by smiths** [smiths/caseStudies#28]
Please review the documentation and create at least 5 issues.

**Comment by deviprasad135** [comment]
@smiths, I have created issues for GlassBR and Game Physics previously. We have even discussed the issues in All Hands Meeting. Do you want me to create issues again?

**Comment by samm82** [comment]
For the sake of checking off an issue, can this issue be closed now? @smiths

**Comment by smiths** [comment]
I am sure that there are still issues with GlassBR, but this particular thread seems to be exhausted.  No new issues will come from leaving this issue open.  Therefore, yes we should close it.
