### ISSUE TITLE
Game Physics: Missing reference in section 2.3 in manual version.

### ISSUE THREAD

**Issue by deviprasad135** [smiths/caseStudies#3]
In the section Organization of Document, there is reference of 1 and 2 in stable but there is no reference in manual.

**Comment by smiths** [comment]
Just do this:

pdflatex <filename.tex>
bibtex <filename.tex>
pdflatex <filename.tex>
pdflatex <filename.tex>

**Comment by deviprasad135** [comment]
It is due to problem with my editor. It is fixed now.

**Comment by smiths** [comment]
Great!  I'll close the issue.
