### ISSUE TITLE
Minor Grammatical Inconsistencies in SRS

### ISSUE THREAD

**Issue by samm82** [smiths/caseStudies#32]
- [x] On line 427: "...A flat and monolithic, glass lite of..." could be "...A flat, monolithic..." to be consistent.

- [x] On line 453: "...Any load lasting 3 s or less", 'seconds' could be spelled out instead of the shorthand '3 s' to match 'days' on line 448: "...Any load lasting approximately 30 days."

- [x] In Table 8 on lines 1395-1399: "\\
${SD_{min}}$ & minimum stand off distance permissible for input & $6.0$ & m
\\
${SD_{max}}$ & maximum stand off distance permissible for input & $130.0$ & m
\\",
'SD<sub>min</sub>' and 'SD<sub>max</sub>' should be switched to match the ordering of the rest of the table [see lines 1385-1394]

**Comment by smiths** [comment]
I agree with all of these proposed changes.  Please make them in both the manual and the generated (and stable) versions.

**Comment by samm82** [comment]
Can be closed with merge of JacquesCarette/Drasil#723
