### ISSUE TITLE
Insufficient General System Description in SRS

### ISSUE THREAD

**Issue by samm82** [smiths/caseStudies#33]
Section 4 of [glassbr_srs.tex](https://github.com/smiths/caseStudies/blob/master/CaseStudies/glass/Documentation/SRS/glassbr_srs.tex) states on lines 322-324: "This section provides general information about the system, identifies the interfaces between the system and its environment, and describes the user characteristics and the system constraints," but only user characteristics and system constraints are provided in Sections 4.1 and 4.2, respectively.  General information and system/environment interfaces are missing.

**Comment by smiths** [comment]
This issue was addressed by #74.  I'll close this issue.  However, I will create another issue because the first sentence of this section isn't quite right.
