### ISSUE TITLE
Broken Link in SRS

### ISSUE THREAD

**Issue by samm82** [smiths/caseStudies#34]
In [glassbr_srs.bib](https://github.com/smiths/caseStudies/blob/master/CaseStudies/glass/Documentation/SRS/glassbr_srs.bib), line 95: " Howpublished = {\href{"www.cs.uic.edu/~i442/VolereMaterials/templateArchive16/c Volere template16.pdf"}{"www.cs.uic.edu/~i442/VolereMaterials/templateArchive16/c Volere template16.pdf"}}," needs a backslash before the tildes, as they aren't being transferred over to the PDF.

**Comment by samm82** [comment]
I fixed the link, but it created a new issue I will post soon - I will check the Drasil now

**Comment by smiths** [comment]
@samm82, I see a reference section in the generated tex file for GalssBR.  I also see the references in the html file.  Do you mean the specific reference you have noticed is incorrect?

**Comment by smiths** [comment]
@samm82, in thinking about it again, please delete the link for the Volere template in the reference.  The Volere template isn't a public resource, so any link we give will not be accessible to everyone.  We should just use the standard citation.  In BibTeX the citation is something like:

`@inbook{RobertsonAndRobertson1999Vol,
	Address = {New York, NY, USA},
	Author = {Suzanne Robertson and James Robertson},
	Chapter = {Volere Requirements Specification Template},
	Date-Added = {2017-09-28 14:24:37 +0000},
	Date-Modified = {2017-09-28 14:24:37 +0000},
	Pages = {353--391},
	Publisher = {ACM Press/Addison-Wesley Publishing Co},
	Title = {Mastering the Requirements Process},
	Year = {1999}}
`

**Comment by samm82** [comment]
So how should I modify the link in my previous comment?

**Comment by smiths** [comment]
You should delete the link.  You should modify the bib file to include the new reference that I sent.  All citations in the tex file that previously pointed to the Volere template should point to this proper reference.

**Comment by samm82** [comment]
There isn't a References.bib file in glass - this is related to #92. Should I make one and add this source?

**Comment by smiths** [comment]
Yes to both.  You should change the Volere reference in the existing bib file and you should move and rename the bib file as you suggested.  This will also involve changing the LaTeX file so that it can still find the bib file.  In the LaTeX file you need to give the path to the new References.bib file.

**Comment by smiths** [comment]
@samm82, please move the contents of the misc/Reference folder to the refs folder.

**Comment by smiths** [comment]
I've verified that the new srs file compiles and that the bibtex entry for the Volere template looks as expected.  Great!
