### ISSUE TITLE
Review documentation and code for no-pcm (solar water heating only)

### ISSUE THREAD

**Issue by smiths** [smiths/caseStudies#40]
Review the documentation and code and create at least 5 issues.

**Comment by elwazana** [comment]
@smiths Should I close this issue Dr. Smith, I've finished reviewing the documentation and code. I asked Maryam, and you told her not to so I just wanted to check with you.

**Comment by elwazana** [comment]
I've reviewed the documentation through again along with the code, I can't see any other issues but if any pop up I'll re-open this issue and assign myself to it.

**Comment by smiths** [comment]
Sounds reasonable.
