### ISSUE TITLE
Unclear Paragraph in MG

### ISSUE THREAD

**Issue by samm82** [smiths/caseStudies#42]
The following paragraph from Section 1, lines 101-110 of [glassbr_mg ](https://github.com/smiths/caseStudies/blob/master/CaseStudies/glass/Documentation/MG/glassbr_mg.tex) might be more clear as a bullet list:
![snip](https://user-images.githubusercontent.com/35857611/39579083-e3159bca-4eb3-11e8-830c-fee075d6cea8.JPG)

**Comment by smiths** [comment]
Interesting idea.  We can leave the current version as a sequence of sentences, but in the future, the Drasil version could have stylist choices like this as configurable parameters.
