### ISSUE TITLE
Glass-BR: Improper position of Figure 1

### ISSUE THREAD

**Issue by deviprasad135** [smiths/caseStudies#44]
I think figure 1 should be placed very next to section 6.1.2 instead of section 6.1.3
![improper figure location](https://user-images.githubusercontent.com/30101689/39760327-09904910-52a3-11e8-82e5-781def0a4dc0.PNG)

**Comment by smiths** [comment]
LaTeX decides where the figures are placed.  LaTeX treats the figures as floats.  The source tex file can make suggestions, but LaTeX decides based on its own rules.  There really isn't anything to change in the source code.
