### ISSUE TITLE
SSP : Data constraints section does not contain any uncertainty values

### ISSUE THREAD

**Issue by niazim3** [smiths/caseStudies#46]
(Issue #27 )

In section 4.2.6 (i.e. Data Constraints), the use of values in the uncertainty column of the table is described, however, there are no values in the table itself.

Perhaps it can be removed completely?

Or is information missing from the SRS?

![image](https://user-images.githubusercontent.com/28247301/39637421-ea881c7e-4f90-11e8-8c2e-10eaa13072ab.png)

(https://github.com/smiths/caseStudies/blob/220c839436f38aaf2c87c4020d0ca23a278fa6c0/CaseStudies/ssp/Documentation%20Files/SRS_SSP.tex#L2961)

**Comment by smiths** [comment]
No, we shouldn't remove the information.  We'll never remember to put it back in if we remove it now.  Please enter 10\% as the uncertainty for everything.  If in doubt, this is the value that engineers usually assume, since they know they can't really do much better than this is general.

**Comment by niazim3** [comment]
This change has been implemented in Drasil already, the only difference being the format of the Typical Uncertainty (i.e. "10%" vs "0.1").

**Comment by niazim3** [comment]
Sorry @smiths, I didn't mention that the manual version has been implemented already (commit that references this issue before my comment).

As for 10% vs the note in Drasil, I'll look into it now.

**Comment by smiths** [comment]
Sounds good.

**Comment by niazim3** [comment]
```
-- | UncertQ is a chunk which is an instance of UncertainQuantity. It takes a 
-- ConstrainedChunk and a Double (from 0 to 1) which represents a percentage of uncertainty
data UncertainChunk  = UCh { _conc :: ConstrainedChunk
                           , _unc' :: Maybe Double
                           }
makeLenses ''UncertainChunk
```
Currently, the uncertainty is stored as a value between 0 and 1 (which is why 0.1 is output at the moment). Since 10% is preferred to 0.1, working on updating the output to be in percent format in the following branch: [displayingUncrtntyUpdate](https://github.com/JacquesCarette/Drasil/tree/displayingUncrtntyUpdate).
