### ISSUE TITLE
SSP : SRS Likely Changes Section contains no content

### ISSUE THREAD

**Issue by niazim3** [smiths/caseStudies#47]
(Issue #27 )

Missing information from SRS or can be removed completely?

https://github.com/smiths/caseStudies/blob/220c839436f38aaf2c87c4020d0ca23a278fa6c0/CaseStudies/ssp/Documentation%20Files/SRS_SSP.tex#L3101-L3105

**Comment by smiths** [comment]
As we discussed in our meeting on Tuesday, we don't want to delete sections that are part of the template.  If we delete them, they are potentially lost forever.  It is better to leave a section with the entry Not Applicable (NA) than to delete it.

Having said that, I think we should be able to list likely changes for SSP.  Can you attempt creating something?  I'll have a look at it when you are done.  Include likely changes that are related to assumptions that you think are reasonable to want to change.  GlassBR has examples of likely changes that are related to assumptions.

**Comment by niazim3** [comment]
The following assumption "The different layers of the soil are homogeneous, with consistent soil properties throughout, and independent of dry or saturated conditions, with the exception of unit weight." can be used to make the following likely changes:

**1. The system currently assumes the different layers of the soil are homogeneous. In the future, implementation can be added for inconsistent soil properties throughout.
2. The software may be changed to accommodate dry or saturated conditions.**

The remaining assumptions are talking about linear relationships between constants and seem deeply intertwined with the calculations, so I'm not sure how much can be changed about this:

"A5: Interslice normal and shear forces have a linear relationship, proportional to a constant (λ) and an interslice force function (f) depending on x position.
A6: Slice to base normal and shear forces have a linear relationship, dependent on the factor of safety FS, and the Coulomb sliding law.
A7: The stress-strain curve for interslice relationships is linear with a constant slope.
A8: The slope and slip surface extends far into and out of the geometry (z coordinate). This implies plane strain conditions, making 2D analysis appropriate.
A9: The effective normal stress is large enough that the resistive shear to effective normal stress relationship can be approximated as a linear relationship.
A10: The surface and base of a slice between interslice nodes are approximated as straight lines."

**Comment by niazim3** [comment]
**2. Changes in input format of the parameters
3. Changes in constant values**

**Comment by smiths** [comment]
Great start @niazim3.  I agree with your first likely change ("inhomogeneous..").  You were right cross out the one about dry or saturated conditions, since (I believe) the choices of inputs already handles this situation.  I also agree that A5 to A10 are too "baked" into this example to be likely changes.  If someone needed to make these changes, they would use a different algorithm.

I like your second likely change ("Changes in input format"), but I would not list this likely change in the SRS.  The change in input format is a likely change for the design stage.

For your third likely change, are there constant values in the SRS?  For any values that are inputs, they are already identified as likely changes by the nature of being inputs.  If there are values that are characterized as constants, I agree that changing the values of the constants is a likely change.

**Comment by JacquesCarette** [comment]
unlikely changes? [i.e. A5-A10] ?

**Comment by smiths** [comment]
Unlikely changes haven't previously been part of the SRS template, but I like the idea.  We have a section for unlikely changes in the module guide for the design, so why not have the same in the SRS?  @niazim3, please add a section for Unlikely Changes to the SRS for SSP.  We can then review it and decide whether we want to push this idea to all of the case studies.

**Comment by niazim3** [comment]
### Re: Constants for Likely Changes

Well there are no auxiliary constants in SSP, however, there are constants like 

**Ψ** ("Constant: converts mobile shear without the influence of interslice forces, to a calculation considering the interslice forces") 

,

**Φ** ("Constant: converts resistive shear without the influence of interslice forces, to a calculation considering the interslice forces").

Although I do not think that they are likely to change since "The constants Ψ and Φ described in equation (20) and equation (19) _are functions of the unknowns_: the interslice normal/shear force ratio λ (IM2) and the factor of safety FS (IM1)."

Since they are functions of the unknown, I think they are related to your point earlier about them already being "likely changes by the nature of being inputs".

Other constants include **κ**, **a**, and **A**; however, not much information is available about them in the SRS, so I'm unsure how to regard these...
![image](https://user-images.githubusercontent.com/28247301/41237206-faea3a1e-6d60-11e8-969f-24a6b9a36269.png)
Descriptions: "Constant: FIXME: missing description"

***

### Re: Unlikely Change Creation
Would it be possible to get some feedback on the following for the Unlikely Changes section?

"If changes were to be made with regard to the following, a different algorithm would be needed.
1. Changes related to assumptions 5 and 6 are not possible due to the dependency of the calculations on the linear relationship between interslice normal and shear forces.
2. Assumption 8 allows for 2D analysis with these models only because stress along z-direction is zero. These models do not take into account stress in the z-direction, and therefore cannot be used without manipulation to attempt 3D analysis."

**Comment by smiths** [comment]
The SSP example is definitely in need of a physics review.  I just looked up the explanation of Psi and Phi in the document and  I don't like what I read.  I don't have time to delve into it right now, but how can constants be "are functions of the unknowns".  This implies that Psi and Phi change depending on the inputs, which suggests that they aren't constant.  Psi and Phi are used for the derivation, not in the actual calculations, but the language around them doesn't seem right to me.  With respect to the current issue, changing Psi and Phi are definitely not likely changes.  (I wouldn't call them unlikely changes either.  Their purpose is more for explaining the derivation.)

I had to look up kappa, a and A in the document.  I see now that they appear as part of the input for the constitutive equation for shear stiffness.  That makes these quantities material properties.  Actually, kappa is listed as an input for the shear stiffness, but it doesn't appear in the equation?  Strange!?  I am still fairly certain that these are material properties, which means that they are inputs for the analysis.  They are inputs that are constant for each run, but they can change between different executions.  They aren't likely changes, just inputs.

Your first pass at the unlikely changes section looks good to me.

**Comment by niazim3** [comment]
Should these changes be propagated to Drasil (i.e. likely change addition, creation of unlikely changes for SSP) and the other case studies (i.e. creation of an Unlikely Changes section)?

**Comment by smiths** [comment]
Yes.  😄

**Comment by niazim3** [comment]
This issue can closed since the remaining tasks are awaiting a merge in Drasil/implementation for other case studies, referenced above.

**Comment by smiths** [comment]
Sounds good.
