### ISSUE TITLE
GlassBR - Typo in MIS Tex

### ISSUE THREAD

**Issue by samm82** [smiths/caseStudies#49]
On line 12 of the[ glassbr_mis.tex](https://github.com/smiths/caseStudies/blob/master/CaseStudies/glass/Documentation/MIS/glassbr_mis.tex) file: `\usepackage{pdfpage}`, "pdfpage" should be "pdfpages"

**Comment by smiths** [comment]
You are correct.  Good work.  I just fixed the code in commit ef55829.
