### ISSUE TITLE
Game Physics: Missing references in section 4.2.1 in manual version.

### ISSUE THREAD

**Issue by deviprasad135** [smiths/caseStudies#5]
In section 4.2.1 Assumptions, there are references in stable version but not in manual version.

**Comment by szymczdm** [comment]
Intro paragraph (with references) from stable should be moved to manual.

**Comment by deviprasad135** [comment]
In section 4.2.1 Assumptions, Intro paragraph is moved form stable to manual. Commit 4d5c5ac

**Comment by smiths** [comment]
Looks good.  We can close this issue.
