### ISSUE TITLE
SolarHeatingWaterOnly_SRS: Incorrect Spacing

### ISSUE THREAD

**Issue by elwazana** [smiths/caseStudies#57]
One of the sentences in the middle of the paragraph in section 2.4 does not have a space following it.

**Comment by elwazana** [comment]
"...additional information they require.The goal statements are..."
https://github.com/smiths/caseStudies/blob/e49e302bbf1aa803dcf4c8f782f8b0066c7e10c3/CaseStudies/SolarHeatingWaterOnly/SRS/SRS.tex#L385

**Comment by elwazana** [comment]
35d27d19473fd71afb7739879bd5bb1017c196ed

**Comment by smiths** [comment]
Good catch.
