### ISSUE TITLE
GlassBR - References not in Table of Contents of SRS

### ISSUE THREAD

**Issue by samm82** [smiths/caseStudies#60]
In [glassbr_srs.pdf](https://github.com/smiths/caseStudies/blob/master/CaseStudies/glass/Documentation/SRS/glassbr_srs.pdf), the References section does not show up in the Table of Contents as a section (it should be number 11 between Auxiliary Constants and Appendix: 
![toc](https://user-images.githubusercontent.com/35857611/39637836-29965bbe-4f92-11e8-9d56-883050c35799.JPG)

The References section is present, it just doesn't have number 11 and is not in the Table of Contents:
![ref](https://user-images.githubusercontent.com/35857611/39637870-4bfc6aae-4f92-11e8-8e50-0d080135216d.JPG)

**Comment by JacquesCarette** [comment]
The answers on
https://tex.stackexchange.com/questions/8458/making-the-bibliography-appear-in-the-table-of-contents

There is a variant on
https://tex.stackexchange.com/questions/246933/how-to-number-references-section-using-bibliography-command
