### ISSUE TITLE
SSP : Potential Problems within MIS Document

### ISSUE THREAD

**Issue by niazim3** [smiths/caseStudies#61]
(Issue #27)

- [x] Start "Notation" section on a newpage after table of contents for formality
- [x] "it's" needs to have the apostrophe removed due to its use in a possessive context (https://github.com/smiths/caseStudies/blob/0f4f403445fab607ae5b6d767fc19dd271a45a7f/CaseStudies/ssp/Documentation%20Files/MIS_SSP.tex#L91)
- [x] remove unnecessary comma (https://github.com/smiths/caseStudies/blob/0f4f403445fab607ae5b6d767fc19dd271a45a7f/CaseStudies/ssp/Documentation%20Files/MIS_SSP.tex#L129)
- [ ] section 3 Module Guide links broken (https://github.com/smiths/caseStudies/blob/0f4f403445fab607ae5b6d767fc19dd271a45a7f/CaseStudies/ssp/Documentation%20Files/MIS_SSP.tex#L157-L165)
- [x] "struc" is used multiple times throughout the document, perhaps adding a point saying that it will be mentioned as "struc" from this point forward (https://github.com/smiths/caseStudies/blob/0f4f403445fab607ae5b6d767fc19dd271a45a7f/CaseStudies/ssp/Documentation%20Files/MIS_SSP.tex#L114)
- [x] "the" needs to be capitalized in 2 places (https://github.com/smiths/caseStudies/blob/0f4f403445fab607ae5b6d767fc19dd271a45a7f/CaseStudies/ssp/Documentation%20Files/MIS_SSP.tex#L1288, https://github.com/smiths/caseStudies/blob/0f4f403445fab607ae5b6d767fc19dd271a45a7f/CaseStudies/ssp/Documentation%20Files/MIS_SSP.tex#L1134) 
- [x] ~~missing references to `sec:MPMod`~~ (e.g. https://github.com/smiths/caseStudies/blob/0f4f403445fab607ae5b6d767fc19dd271a45a7f/CaseStudies/ssp/Documentation%20Files/MIS_SSP.tex#L127) no update necessary
- [x] ~~are the hardcoded "??"'s supposed to be there?~~(https://github.com/smiths/caseStudies/blob/0f4f403445fab607ae5b6d767fc19dd271a45a7f/CaseStudies/ssp/Documentation%20Files/MIS_SSP.tex#L1190-L1193)

**Comment by niazim3** [comment]
Does Drasil work to create an MIS? I don't think I can check Drasil for any changes necessary for propagation...

**Comment by JacquesCarette** [comment]
It used to have facilities to do that (create MIS), but it was such a horrible hack that we ripped it out. There was no 'link' between the MIS and anything else, so no way to do either traceability or consistency checking.  Which was contrary to our whole philosophy.

**Comment by smiths** [comment]
@niazim3,  you only need to worry about updating the manual version of the MIS.  Unlike the SRS, there is no corresponding Drasil version.  This is actually a good thing in the sense that the MIS for SSP is rather weak.  Eventually it will need massive changes, and that would cause major headaches if we had to maintain both a manual and a Drasil version.

**Comment by niazim3** [comment]
Created issue for "broken" module guide links that actually weren't broken. This issue can now be closed.
