### ISSUE TITLE
GlassBR: Inconsistency in Error Message in calculations.py

### ISSUE THREAD

**Issue by samm82** [smiths/caseStudies#65]
In caseStudies/CaseStudies/glass/Implementations/Python/Implementation/calculations.py, line 52, the error message should read "Error: q_hat(DD6 in **the** SRS) is out of bounds...." to be consistent with the one on line 50:

Line 50:
https://github.com/smiths/caseStudies/blob/a7e8172200744cf297aab9ab861c72a2befda9d7/CaseStudies/glass/Implementations/Python/Implementation/calculations.py#L50
Line 52:
https://github.com/smiths/caseStudies/blob/a7e8172200744cf297aab9ab861c72a2befda9d7/CaseStudies/glass/Implementations/Python/Implementation/calculations.py#L52

**Comment by smiths** [comment]
The error messages are not in the current version of the implementation.  (The version that was previously Python_simplified.)

We should add the exceptions back to the implementation.  Can you please create an issue for that?
