### ISSUE TITLE
GlassBR: Grammar Issue in derivedValues.py

### ISSUE THREAD

**Issue by samm82** [smiths/caseStudies#67]
On line 46 of both caseStudies/CaseStudies/glass/Implementations/Python/Implementation/derivedValues.py and caseStudies/CaseStudies/glass/Implementations/Python_Simplified/Implementation/derivedValues.py, the line should read: "Wrong thickness entered - Not an industrial standard" instead of what is shown:

Python
https://github.com/smiths/caseStudies/blob/a7e8172200744cf297aab9ab861c72a2befda9d7/CaseStudies/glass/Implementations/Python/Implementation/derivedValues.py#L46

Python_Simplified
https://github.com/smiths/caseStudies/blob/a7e8172200744cf297aab9ab861c72a2befda9d7/CaseStudies/glass/Implementations/Python_Simplified/Implementation/derivedValues.py#L46

**Comment by smiths** [comment]
@samm82, please proceed with making the proposed change to improve the text of the error message.  It looks like the generated code (Drasil repo) does not check the validity of the inputs, so this change shouldn't propagate to that repo.  If you could verify this, that would be great.

**Comment by samm82** [comment]
@smiths you are correct - this change doesn't propagate.
