### ISSUE TITLE
SolarHeatingWaterOnly/SRS: Tearing Issue 

### ISSUE THREAD

**Issue by elwazana** [smiths/caseStudies#69]
Between Sections 5.1 and 6 a tear in the pdf a appears and subsection 5.2 disappears.

I've tried looking through the SRS.tex file to spot the error but I couldn't locate it. 

![image](https://user-images.githubusercontent.com/35268928/39821537-78a292bc-5376-11e8-844f-09df2d1b121a.png)

**Comment by smiths** [comment]
I fixed this problem in commit 0179d31.  The problem was the longtable environment that was being used.  It was confusing LaTeX, so I changed it to a tabular environment.  The table of values is not that long, so tabular should be fine.
