### ISSUE TITLE
Game Physics: MG Inconsistency

### ISSUE THREAD

**Issue by Mornix** [smiths/caseStudies#72]
(Issue #29)

The [Game Physics MG](https://github.com/smiths/caseStudies/blob/master/CaseStudies/gamephys/documentation/MG/GamePhysicsMG.pdf) has an inconsistency between Section 5 and Section 6. 

Section 5 refers to the modules in some programming language in the general sense while Section 6 makes direct mention of the C modules which seems like an inconsistency between the sections. 

<img width="853" alt="screen shot 2018-05-09 at 11 20 52 pm" src="https://user-images.githubusercontent.com/1929800/39850677-a50a5cda-53e0-11e8-8c22-ac24ed7a97d6.png">
<img width="858" alt="screen shot 2018-05-09 at 11 21 05 pm" src="https://user-images.githubusercontent.com/1929800/39850680-a6a4145a-53e0-11e8-83af-af8618d87053.png">

**Comment by smiths** [comment]
Agreed.  The MG should be language agnostic, if at all possible.  It certainly is possible in this case.  Can you please modify the MG so that Section 6 mentioned implemented code files, not specifically C files.
