### ISSUE TITLE
Write a System Context Section

### ISSUE THREAD

**Issue by smiths** [smiths/caseStudies#74]
As discussed in #43, please add a System Context section to GlassBR.  You can follow the example from SWHS on what the system context should look like.  You are basically drawing the boundary between the software's responsibilities and the user's.  When you are done, I'll review your text and we'll decide how to propagate this change to the other examples and to the Drasil generated documents.

**Comment by deviprasad135** [comment]
@smiths, Can I use the following introduction which is in SWHS, for GlassBR also?
![capture](https://user-images.githubusercontent.com/30101689/40731074-4bf8cf04-63fe-11e8-8d9f-6fd40f4c6a2e.PNG)

**Comment by smiths** [comment]
@deviprasad135, yes you can use something similar to this.  Of course the name of the software is different and the text characterizing the outputs would be different.

**Comment by deviprasad135** [comment]
@smiths, I have added the System Context section to Glass-BR. Can I push it to the repository?

**Comment by smiths** [comment]
Yes, push it so that I can review it.  Please give the hash code for the commit that includes the new section.

**Comment by deviprasad135** [comment]
@smiths, commit # 80250c2...f359c47

**Comment by smiths** [comment]
Your documentation for system context section was close.  I made some changes (2fb2756) to complete the section.

We can close this issue, but before doing so, please do the following:

- Add an issue to the Drasil repo (assigned to @deviprasad135) for updating the Drasil version of the GlassBR SRS to include the system context section.
- Create issues for any other case studies that do not include the system context section asking for this section to be added.  You should assign these issues to the "owners" of each of the case studies.  You should have a pointer to this issue in the text of each of these new issues to show where this request is coming from.

**Comment by smiths** [comment]
The system context is now added to GlassBR, so we can close this issue.
