### ISSUE TITLE
Incorrect Input File

### ISSUE THREAD

**Issue by samm82** [smiths/caseStudies#76]
While working on #68, I came across this: in most, if not all input files, the thickness is given as an integer, eg. "10":

https://github.com/smiths/caseStudies/blob/0179d31a12e359ac6fa69f9ec341d8d5aa71ac35/CaseStudies/glass/Implementations/Python/defaultInput.txt#L1-L4

However, it is required that it be described as a float, eg. "10.0":

https://github.com/smiths/caseStudies/blob/0179d31a12e359ac6fa69f9ec341d8d5aa71ac35/CaseStudies/glass/Implementations/Python/Implementation/checkConstraints.py#L19-L20

https://github.com/smiths/caseStudies/blob/0179d31a12e359ac6fa69f9ec341d8d5aa71ac35/CaseStudies/glass/Implementations/Python/Implementation/derivedValues.py#L45-L46

**Comment by samm82** [comment]
@smiths So change # to #.0 in all the input files? Is that what you mean by update the test cases?

**Comment by smiths** [comment]
Yes.  Please make the change.
