### ISSUE TITLE
Fill in Blank README.md

### ISSUE THREAD

**Issue by samm82** [smiths/caseStudies#79]
The placeholder [README.md in CaseStudies/glass/Implementations/C](https://github.com/smiths/caseStudies/blob/master/CaseStudies/glass/Implementations/C/README.md) should be filled in with the appropiate information.

**Comment by smiths** [comment]
I've added a bare bones version of the README.md file in commit 8973954.

The C code does not currently work.  Running it, at least on my machine, causes a segmentation fault.  I'm actually surprised that such simple code is causing so much trouble.  However, I'm not sure if fixing the manual version of the C code is a worthwhile task.  With the code generation we can generate the C code directly.  We will only update the C code if doing so will help us with the generated version.  At this point, I don't think it is necessary.
