### ISSUE TITLE
SolarHeatingWaterOnly: Correct Comments in Python

### ISSUE THREAD

**Issue by samm82** [smiths/caseStudies#87]
In Python, comments are denoted by `#comment`, not by `"""comment"""`. Yes triple quotes can act as comments, but they actually create a multi-line string that is garbage collected if not used (ie. assigned to a variable, etc.). Depending on their placement, they can actually mess up the code. Comments throughout the Python Implementation in SolarHeatingWaterOnly should be replaced to reflect this, simply to follow convention if not to avoid errors.

#86

**Comment by smiths** [comment]
Please don't assign this to me.  Assign it to the owner (summer student) for the case study.  In this case, I believe it is @elwazana

**Comment by elwazana** [comment]
@samm82 @smiths There are no occurrences of `"""comment"""` in the SolarWaterHeatingOnly example

**Comment by smiths** [comment]
Thank you for the investigation @elwazana.
