### ISSUE TITLE
Naming SSP

### ISSUE THREAD

**Issue by niazim3** [smiths/caseStudies#88]
Currently, the name of the SSP case study's program is SSA and is mentioned as "SSA program", "SSA Program", or just "SSA" throughout the documents. For the sake of consistency, SSP can become the contracted name for "Slope Stability Program". Ensuring that one name is used throughout the example case study will allow for small but beneficial changes in the future if necessary such as renaming and avoiding confusion that may arise through verbal communication (because of it being dubbed as SSP).

**Comment by niazim3** [comment]
Closes by commits a3e1baca454981bc7ce9ec8c8a40119c64cab22d...645af99b057ccd07b875159d4687328bc88b6caa.

**Comment by smiths** [comment]
Looks great!
