### ISSUE TITLE
Standardization of Case Studies folder structure

### ISSUE THREAD

**Issue by smiths** [smiths/caseStudies#92]
The case studies all have different folder structures and naming conventions.  I believe our lives will be easier going forward if we standardize.  (A point in favour of the generated versions is that this kind of change would be much easier with Drasil.  Something to keep in mind @szymczdm 😄)

Please modify your case study to correspond with the folder structure and naming conventions used at:

https://gitlab.cas.mcmaster.ca/smiths/cas741/tree/master/BlankProjectTemplate

If you do not have content for a given folder, just create the folder with a README.md file as content.  We can update the content in the future.  You do not need the following content:

- No need for the DevelopmentPlan folder
- In the SRS folder, you do not need any of the CA.* files (this is for a commonality analysis, which we are not doing for our current case studies)
- No FinalPresentation folder (this was for the needs of the course, not projects in general)
- No Comments.tex file (this was for adding comments to all of the documents.  We can continue to handle this is an ad hoc way in our projects)

For the LICENSE file, use the file suggested by @JacquesCarette (https://github.com/JacquesCarette/Drasil/blob/master/LICENSE), but with Spencer Smith as the author.

If you have any content not covered by the proposed folder structure, you can create a misc folder and put the content within that folder.

I'll list the assignment of case studies below.  If you have any questions, you can put them in the comments below, or create an issue.

- [x] GlassBR: @samm82 
- [x] GamePhysics: @Mornix 
- [x] SWHS: @elwazana (change swhs repo, not the case studies repo)
- [x] noPCM: @elwazana 
- [x] SSP: @niazim3

**Comment by samm82** [comment]
I had an MIS_new folder that I just moved to Design

**Comment by samm82** [comment]
If the testing files are in Implementation, which I renamed to src, should I move them to test? Or just leave test empty with a README?

**Comment by smiths** [comment]
@samm82 that is fine to move the MIS_new folder.  When we update the MIS, we will only have one document, but for now there is likely useful content in both documents.

For the moment, you can leave tests with just a README.  The content of the README should point readers to your actual tests.  I would like to eventually reorganize the test files so that they use the tests folder, but that won't be a trivial task; it should wait until we refactor the test plan.

**Comment by Mornix** [comment]
@smiths gamephys has what appears to be a [final presentation](https://github.com/smiths/caseStudies/tree/master/CaseStudies/gamephys/presentation). Is a FinalPresentation folder acceptable in this case or should it be placed under misc?

**Comment by smiths** [comment]
@Mornix, I would prefer the presentation to go in the misc folder.  The FinalPresentation folder is really only for my course (CAS 741).

**Comment by Mornix** [comment]
@smiths Is it acceptable to place a shared .bib file (between SRS, and MIS) in the root of the docs/ folder or should this file be duplicated and pruned and placed locally in the relevant leaf folders?

**Comment by smiths** [comment]
I would like the shared bib file in the refs folder.  I don't think it really came through in my original issue, but that would be my preference.

**Comment by niazim3** [comment]
Changes to SSP can be seen in the [updtFileStructureSSP](https://github.com/smiths/caseStudies/tree/updtFileStructureSSP) branch.

**Comment by niazim3** [comment]
@smiths Can the "program + testing" folder (which contains the original program and testing programs) be moved into a misc folder for SSP? Is it something that should be kept at all (since implementation of tests and the program itself seem complete given the files in the "data files" and "module program" folder)?

**Comment by smiths** [comment]
Yes, move the program + testing folder into the misc folder.  I think we should give it a better, more descriptive name.  Maybe something like, Original_ProgAndTests?

If we continue developing ssp, there will likely be a point where the test cases are built as comparisons between the new code and the original code.  It would be good to still have easy access to the original code.

**Comment by niazim3** [comment]
Can this issue be closed?

**Comment by smiths** [comment]
Yes.
