### ISSUE TITLE
Update SSP Force Diagram for Symbol Change

### ISSUE THREAD

**Issue by niazim3** [smiths/caseStudies#99]
As discussed in issue #98, SSP's force diagram needs to be updated for the symbol change that came about from having duplicate `E` symbols (i.e. changing interslice normal force to be denoted by `G` instead of an `E` to remove ambiguity that comes about from elastic modulus also being denoted as `E`). Redrawing of the figure should be tried in **draw.io** so that it can be saved for future editing.

**EDIT: Make sure to remove the note under the ForceDiagram images in relation to the relabelling both this repo and Drasil**

**Comment by smiths** [comment]
@niazim3, looks good.  I assigned this issue to you.  It is still a low priority, but all issues should be assigned to someone.  😄

**Comment by niazim3** [comment]
@smiths Can you please take a look at this?
![forcediagram](https://user-images.githubusercontent.com/28247301/41686227-452c31c0-74b1-11e8-8795-9c05eddc874b.png)

**Comment by smiths** [comment]
Looks good, except, the zeds should be lower case (z, not Z).  What is the source for this figure?  In case there are future edits, please commit the source as well as the figure itself.

**Comment by niazim3** [comment]
Will do, thanks.

Looks like the source is ZhuEtAl2005:
![image](https://user-images.githubusercontent.com/28247301/41977795-46cfa8da-79ee-11e8-8d29-c3b5f97383f9.png), so future edits should have a message referring to said source.

**Comment by smiths** [comment]
@niazim3, I didn't actually mean the source of the original figure, I meant the source code for generating the figure.  How did you draw it?  I would like it to be as easy as possible to make future modifications, so any file used to generate the figure should also be under version control.

**Comment by niazim3** [comment]
Ah I see; I added an .xml file in bbad3f0.

**Comment by smiths** [comment]
Yes, the name of the file is what I was looking for.

Unfortunately, I cannot view your file.  What program is needed to view the xml file?  I can see the xml file, but I can only read it as text.  What program do I need to render it as a picture?

**Comment by niazim3** [comment]
To render it:

- close the `Google Drive` popup that comes up
- open [draw.io](https://www.draw.io/)
- open the `file` tab at the top left
- choose `Import from`
- choose `Device`

and find the ForceDiagram.xml to have it opened up.

**Comment by smiths** [comment]
I wondered if the figure was drawn with draw.io.  I think this is a great idea.  I like draw.io, and everyone has access to it, so your figure should be editable in the future.  Please include the steps you described above in the README.md file in the SRS folder.  That way others in the future will know how to edit this figure.
